#These settings are used to generate the quality you would like
#the code uses movie_to_convert and movie_name to generate
handrake_presets:
    animation:
      ext: .mkv
      opts: "-e x264 -b 1000 -B 160 -R 48 -E faac -f mkv -x ref=5:mixed-refs:bframes=6:bime:weightb:b-rdo:direct=auto:b-pyramid:me=umh:subme=5:analyse=all:8x8dct:trellis=1:nr=150:no-fast-pskip:filter=2,2 -m -d -p -2 -T"
    appletv: 
      ext: .mp4 
      opts: "-e x264 -b 2500 -B 160 -R 48 -E faac -f mp4 -x bframes=3:ref=1:subme=5:me=umh:no-fast-pskip=1:trellis=2:cabac=0 -m -p"
    bedlam:
      ext: .mkv 
      opts: "-e x264 -b 1800 -B 160 -R 48 -E ac3 -f mkv -x ref=16:mixed-refs:bframes=6:bime:weightb:b-rdo:direct=auto:b-pyramid:me=umh:subme=7:me-range=64:analyse=all:8x8dct:trellis=2:no-fast-pskip:no-dct-decimate:filter=-2,-1 -m -p -2 -T"
    broke: 
      ext: .mp4
      opts: "-e x264 -S 695 -B 128 -R 48 -E faac -f mp4 -w 640 -x ref=3:mixed-refs:bframes=6:bime:weightb:b-rdo:b-pyramid:direct=auto:me=umh:subme=6:trellis=1:analyse=all:8x8dct:no-fast-pskip -m -2 -T"
    deux_six: 
      ext: .mkv
      opts: "-e x264 -b 1600 -B 160 -R 48 -E ac3 -f mkv -x ref=5:mixed-refs:bframes=3:bime:weightb:b-rdo:b-pyramid:me=umh:subme=7:trellis=1:analyse=all:8x8dct:no-fast-pskip -m -p -2 -T"
    film:
      ext: .mkv
      opts: "-e x264 -b 2000 -B 160 -R 48 -E ac3 -f mkv -x ref=3:mixed-refs:bframes=3:bime:weightb:b-rdo:direct=auto:b-pyramid:me=umh:subme=6:analyse=all:8x8dct:trellis=1:no-fast-pskip -m -p -2 -T"
    iphone:
      ext: .mp4
      opts: "-e x264b30 -b 960 -B 128 -R 48 -E faac -f mp4 -w 480 -x cabac=0:ref=1:analyse=all:me=umh:subme=6:no-fast-pskip=1:trellis=1 -m"
    iphone4:
      ext: .mp4
      opts: "-e x264b30 --two-pass --vb 1200 -B 128 -R 48 --aencoder faac --format mp4 --maxWidth 960 -x cabac=0:ref=1:analyse=all:me=umh:subme=6:no-fast-pskip=1:trellis=1 -m"
    ipod_high_res:
      ext: .mp4
      opts: "-e x264b30 -b 1500 -B 160 -R 48 -E faac -f mp4 -w 640 -x keyint=300:keyint-min=30:bframes=0:cabac=0:ref=1:vbv-maxrate=1500:vbv-bufsize=2000:analyse=all:me=umh:subme=6:no-fast-pskip=1 -m"
    ps3:
      ext: .mp4
      opts: "-e x264 -b 2500 -B 160 -R 48 -E faac -f mp4 -x level=41:subme=5:me=umh -m -p"
    psp:
      ext: .mp4
      opts: "-b 1024 -B 128 -R 48 -E faac -f mp4 -w 368 -l 208 -m"
    quicktime:
      ext: .mp4
      opts: "-e x264 -b 2000 -B 160 -R 48 -E faac -f mp4 -x ref=3:mixed-refs:bframes=3:bime:weightb:b-rdo:direct=auto:me=umh:subme=5:analyse=all:8x8dct:trellis=1:no-fast-pskip -m -p -2 -T"
    tv:
      ext: .mkv
      opts: "-e x264 -b 1300 -B 160 -R 48 -E faac -f mkv -x ref=3:mixed-refs:bframes=6:bime:weightb:direct=auto:b-pyramid:me=umh:subme=6:analyse=all:8x8dct:trellis=1:nr=150:no-fast-pskip -m -d -2 -T"

dvd_location: DVD